# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 917f7bbe84321c04d726f78b2fa58680227f8f330b5fb940c677b87400c4f9fd8cf117f48b94cab80c98c4c8382693ec2f741d5a06de37852ba3ca031328d3d1

test:
  secret_key_base: d588bca6e73d95d4f5a17d7f7ea3919e03c77caaf588ef046e5ad522694f799b959188b67df287c06f13201771d8dade717eb6aa79215ead95c5ecfd7db88643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
